#import "../../const.typ": Re_cost, Am_cost, An_cost, Ve_cost, Pr_cost, Pt_cost
#import "../../functions.typ": rendicontazioneOreAPosteriori, rendicontazioneCostiAPosteriori, glossary


== Settimo #glossary[sprint]

*Inizio*: Venerdì 05/01/2024

*Fine*: Giovedì 11/01/2024 

#rendicontazioneOreAPosteriori(sprintNumber: "07")

#rendicontazioneCostiAPosteriori(sprintNumber: "07")

=== Analisi a posteriori

Il consuntivo delinea come le ore effettivamente utilizzate nel corso di questo #glossary[sprint] siano risalite rispetto a allo #glossary[sprint] precedente, segno che il ritmo di lavoro del team ha quasi raggiunto il livello che lo caratterizzava prima delle vacanze natalizie. Non sorprende che la maggior parte delle ore siano state investite nel ruolo di Verificatore (come da nuovo preventivo, realizzato nel corso dello #glossary[sprint]), dato che il team si sta ormai impegnando nella revisione in stile #glossary["walkthrough"] della maggior parte della #glossary[documentazione]. Per quanto riguarda il _Piano di Progetto_, il team è stato felice di constatare che la pianificazione a breve termine, in questo caso la pianificazione e il preventivo realizzati precedentemente per lo #glossary[sprint] 8 al termine dello #glossary[sprint] 7, si è rivelata significativamente più sensata e, di conseguenza, utile di quella a lungo termine: in particolare, il Responsabile non ha dovuto aggiornare quanto già deciso per lo #glossary[sprint] 8 in modo significativo, in quanto sia le attività dettagliate nella pianificazione che la ripartizione delle ore per ruolo specificata nel preventivo si sono rivelate particolarmente azzeccate. Si è notato, dunque, come un lieve sforzo aggiuntivo a priori, atto a stabilire le modalità di lavoro dei 2 #glossary[sprint] immediatamente successivi ed effettuato come team piuttosto che da un singolo componente, contribuisca ad alleggerire il carico che grava sul Responsabile. In tal modo, il Responsabile può dedicare maggior tempo alle altre mansioni di sua competenza, tra cui anche la stesura dei consuntivi. Dunque ci si aspetta che i prossimi consuntivi (in particolare quelli successivi alla prima revisione #glossary[RTB]), e in particolare l'analisi a posteriori che li caratterizza, siano ancor più dettagliati e riflettano quanto più possibile l'andamento dello #glossary[sprint] appena concluso e le discussioni che avvengono internamente durante il meeting di #glossary[Sprint Retrospective], come avverrebbe idealmente.

Altra cosa degna di nota per questo #glossary[sprint] è stato l'aggiornamento del preventivo realizzato inizialmente dal team per la candidatura al capitolato, che riporta sempre lo stesso numero di ore a disposizione (570 totali) ma aumenta nel costo, in quanto è stata cambiata la ripartizione delle ore per ruolo, aggiungendone ai ruoli di Amministratore e Analista e sottraendone ai ruoli di Programmatore e Verificatore (come verrà illustrato in dettaglio all'interno della _Lettera di Presentazione_). Questo cambiamento deve essere riportato ed evidenziato all'interno del _Piano di Qualifica_, per cui il team ha deciso di mantenere i dati e i grafici corrispondenti invariati fino allo #glossary[sprint] 6 (dunque il tutto fa riferimento al vecchio BAC), e mostrare come il nuovo BAC modifichi i grafici rilevanti in modo da poter trarre osservazioni aggiornate sull'andamento del progetto all'interno del cruscotto delle metriche. 

Per quanto riguarda i rischi, si è manifestato nuovamente RP3 o "Variazioni nei tempi e costi del progetto", questa volta con riferimento al costo modificato all'interno del preventivo; nel corso dello #glossary[sprint] 4 il rischio si era rivelato difficile da gestire a causa della pianificazione poco flessibile che non aveva preso in considerazione l'eventualità di sostenere la prima revisione #glossary[RTB] più tardi del previsto. Nel corso di quest'ultimo #glossary[sprint], invece, l'implementazione delle prime due misure preventive ha consentito al team di ripensare quanto preventivato inizialmente in modo critico e consapevole: in particolare, si sono potute impiegare ore da Amministratore che non erano più a disposizione per alcuni membri e, di conseguenza, aggiornare i preventivi dello #glossary[sprint] 8 e successivi all'interno della pianificazione a breve termine in modo molto più agevole di quanto non sarebbe stato se il team avesse mantenuto quella a lungo termine. Inoltre, la rendicontazione delle ore produttive effettivamente utilizzate all'interno dello #glossary[spreadsheet] "Time & Resource Manager" si è rivelato di importanza cruciale per mettere a punto dei consuntivi accurati e, di conseguenza, trarre conclusioni utili ad informare la scelta del team di cambiare il rapporto ore e il costo del progetto. Se inizialmente il team non disponeva dei dati o degli strumenti adatti a compiere scelte informate sui tempi e i costi del progetto, ora invece può sfruttare una pianificazione flessibile, consuntivi accurati e i grafici riportati nel _Piano di Qualifica_ per comprendere l'andamento del progetto e continuare a monitorarlo da vicino in futuro.
