@startuml USERCASES

left to right direction

actor amministratorepubblico as "Amministratore pubblico"

rectangle "System" {
  usecase "UC1.1: Visualizzazione della mappa della città" as UC1.1
  usecase "UC1.2: Visualizzazione di indicatori numerici" as UC1.2
  usecase "UC1: Visualizzazione della Dashboard" as UC1
  usecase "UC2.1: Visualizzazione della mappa della cella" as UC2.1
  usecase "UC2.2: Visualizzazione di indicatori numerici della cella" as UC2.2
  usecase "UC2: Visualizzazione dello stato di una cella" as UC2
  usecase "UC3: Visualizzazione del registro dei sensori" as UC3
  usecase "UC4: Selezione di un sensore" as UC4
  usecase "UC5: Modifica dello stato di un sensore" as UC5
  usecase "UC6: Visualizzazione dati in intervalli selezionati" as UC6
  usecase "UC7: Allarmi del sistema" as UC7
  usecase "UC7.1: Allarmi per rilevazione anomalie" as UC7.1
  usecase "UC7.2: Allarmi per superamento soglie" as UC7.2
  usecase "UC8: Accesso all'archivio delle anomalie rilevate" as UC8
  usecase "UC9: Modifica della soglia di rilevazione sensoriale" as UC9
  usecase "UC10: Analisi dei trend" as UC10
  usecase "UC11: Analisi avanzata dei sensori" as UC11
  usecase "UC11.1: Correlazione tra tipologie di sensori" as UC11.1
  usecase "UC11.2: Confronto tra celle della città" as UC11.2
  usecase "UC12: Filtraggio dei sensori" as UC12
 

  amministratorepubblico --> UC1
  amministratorepubblico --> UC3
  UC1.1 -|> UC1
  UC1.2 -|> UC1
  UC2 .up.> UC1 : <<extend>>
  UC2 <|- UC2.1
  UC2 <|- UC2.2
  UC4 .up.> UC2.2 :<<extend>>
  UC4 .up.> UC3 :<<extend>>
  UC12 .up.> UC3 :<<extend>>
  UC5 .up.> UC4 :<<extend>>
  UC6 .up.> UC4 :<<extend>>
  UC10 .up.> UC6 :<<extend>>
  amministratorepubblico --> UC7
  UC7 <|- UC7.1
  UC7 <|- UC7.2
  amministratorepubblico --> UC9
  amministratorepubblico --> UC8
  amministratorepubblico --> UC11
  UC11 <|- UC11.1
  UC11 <|- UC11.2

}
@enduml