name: Development
run-name: Test & Publish
on:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # exept for main
jobs:
  check-glossary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check Glossary
        run: python3 src/glossary_check.py

  test-and-publish:
    runs-on: ubuntu-latest
    needs: check-glossary
    steps:
      - name: Setup Typst
        uses: typst-community/setup-typst@v3.1.0
        with:
          typst-version: 0.10.0
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile documents
        run: |
          cd ${{ github.workspace }}/src
          chmod +x *.sh
          ./build_all.sh
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documentazione
          path: |
            build
