name: Typst
run-name: Compiling Typst & Build Artifacts
on: [push]
jobs:
  compile-typst-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Installing Typst
        run: |
            brew install typst
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile documents and set up artifacts
        run: |
          cd ${{ github.workspace }}/src
          chmod +x *.sh
          ./build_all.sh
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documentazione
          path: |
            build