name: Typst
run-name: Test, Publish & Deploy
on: [push]
#on:
#  push:
#    branches:
#      - main
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Installing Typst
        run: |
            brew install typst
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile documents
        run: |
          cd ${{ github.workspace }}/src
          chmod +x *.sh
          ./build_all.sh
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documentazione
          path: |
            build
  deploy:
    runs-on: ubuntu-latest
    needs: test-and-publish
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Documentazione
          path: /home/runner/work/Docs/Documentazione
      - name: Download Facing Repo
        uses: actions/checkout@v2
        with:
          repository: SWATEngineering/SWATEngineering.github.io
      - name: Clean Artifacts
        continue-on-error: true
        run: |
          rm -r ../Documentazione/2_RTB/VerbaliEsterni
      - name: Clean Facing Repo
        continue-on-error: true
        # Elimino tutti i file dalla repo di vetrina tranne i Verbali Esterni, essendo quelli firmati da tenere
        run: |
          find ./2_RTB -mindepth 1 -not -path './2_RTB/VerbaliEsterni/*' -delete
      - name: Update Facing Repo
        run: |
          mkdir -p "./2_RTB" && cp -r ../Documentazione/2_RTB/* ./2_RTB/
      - name: Check Test
        run: |
          ls -la
          ls -la ./2_RTB
          git status