name: Typst
run-name: Test, Publish & Deploy
on: [push]
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Installing Typst
        run: |
            brew install typst
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile documents
        run: |
          cd ${{ github.workspace }}/src
          chmod +x *.sh
          ./build_all.sh
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documentazione
          path: |
            build
  deploy:
    runs-on: ubuntu-latest
    needs: test-and-publish
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Documentazione
          path: /home/runner/work/Docs/Documentazione
      - name: Download Facing Repo
        uses: actions/checkout@v2
        with:
          repository: SWATEngineering/SWATEngineering.github.io
      - name: Clean Artifacts
        run: |
          ls -la ../Documentazione/2_RTB/
          rm -r ../Documentazione/2_RTB/VerbaliEsterni
          ls -la ../Documentazione/2_RTB/